name: Convert Markdown to PDF

on:
  workflow_dispatch: # 手動実行を可能にするトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v3

    - name: Dockerコンテナで日本語PDFを生成
      uses: addnab/docker-run-action@v3
      with:
        image: paperist/alpine-texlive-ja:latest
        options: --rm
        run: |
          # pandocをインストール
          apk add --no-cache pandoc
          # Markdownファイルが存在することを確認
          if [ ! -f sample.md ]; then echo "Error: sample.md not found"; exit 1; fi
          # PDFを生成
          pandoc sample.md -o output.pdf --pdf-engine=lualatex

    - name: PDFをアップロード
      uses: actions/upload-artifact@v3
      with:
        name: converted-pdf
        path: output.pdf
