name: Convert Markdown to LaTeX

on:
  workflow_dispatch:  # 手動実行を有効にする

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Extract title from Markdown
        id: extract_title
        run: |
          # sample.mdの最初の行をタイトルとして抽出
          TITLE=$(head -n 1 sample.md | sed 's/^# //')
          echo "TITLE=$TITLE" >> $GITHUB_ENV  # GitHub Actionsの環境変数に設定
          echo "Extracted title: $TITLE"  # ログにタイトルを出力して確認
      - name: Convert sample.md to sample.tex using template
        run: |
          # MarkdownからLaTeXに変換し、テンプレートを使ってPDFを作成
          pandoc -r markdown-auto_identifiers sample.md -o sample.tex --template=template.tex -V title="$TITLE"
          
      - name: Display sample.tex content
        run: cat sample.tex

      - name: Compile sample.tex to DVI using platex
        run: |
          docker run --rm -v $PWD:/workdir paperist/alpine-texlive-ja platex /workdir/sample.tex
      - name: Generate PDF from DVI using dvipdfmx
        run: |
          docker run --rm -v $PWD:/workdir paperist/alpine-texlive-ja dvipdfmx /workdir/sample.dvi
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdf
          path: sample.pdf
