name: Convert Markdown to LaTeX

on:
  workflow_dispatch:  # 手動実行を有効にする

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Convert sample.md to sample.tex
        run: pandoc -r markdown-auto_identifiers sample.md -o sample.tex

      - name: Display sample.tex content
        run: cat sample.tex

      - name: Run LaTeX with paperist/alpine-texlive-ja
        run: |
          docker run --rm -v $PWD:/workdir paperist/alpine-texlive-ja pdflatex /workdir/sample.tex
