name: Convert Markdown to PDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: チェックアウトリポジトリ
      uses: actions/checkout@v3

    # Markdown → TeX (pandoc/coreを使用)
    - name: MarkdownをTeXに変換
      uses: docker://pandoc/core:latest
      with:
        args: sample.md -o sample.tex --template=template.tex

    # TeX → PDF (paperist/alpine-texlive-jaを使用)
    - name: TeXをPDFに変換
      uses: addnab/docker-run-action@v3
      with:
        image: paperist/alpine-texlive-ja:latest
        options: -v ${{ github.workspace }}:/workspace -w /workspace
        run: |
          lualatex sample.tex

    # PDFをアップロード
    - name: PDFをアップロード
      uses: actions/upload-artifact@v3
      with:
        name: converted-pdf
        path: sample.pdf
