name: Convert Markdown to LaTeX

on:
  workflow_dispatch:  # 手動実行を有効にする

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install pandoc
        run: sudo apt-get install pandoc

      - name: Convert sample.md to sample.tex using template
        run: |
          pandoc -r markdown-auto_identifiers sample.md -o sample.tex --template=template.tex --no-ligatures


      - name: Display sample.tex content
        run: cat sample.tex

      - name: Compile sample.tex to PDF using LaTeX
        run: |
          # platex でコンパイル (日本語対応)
          docker run --rm -v $PWD:/workdir paperist/alpine-texlive-ja platex /workdir/sample.tex
          # dvipdfmx で PDF 生成
          docker run --rm -v $PWD:/workdir paperist/alpine-texlive-ja dvipdfmx /workdir/sample.dvi

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-pdf
          path: sample.pdf
